// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MooolApp.Models;

#nullable disable

namespace MooolApp.Migrations
{
    [DbContext(typeof(DbMool))]
    [Migration("20250503175056_four1")]
    partial class four1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MooolApp.Models.Address", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MoolId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MoolId")
                        .IsUnique();

                    b.ToTable("Address");
                });

            modelBuilder.Entity("MooolApp.Models.Item", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MoolID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MoolID");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Description = "this is very nice",
                            MoolID = "2",
                            Name = "colths",
                            price = 2440.0
                        });
                });

            modelBuilder.Entity("MooolApp.Models.Mool", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Mools");

                    b.HasData(
                        new
                        {
                            Id = "2",
                            Name = "kaseon"
                        });
                });

            modelBuilder.Entity("MooolApp.Models.Address", b =>
                {
                    b.HasOne("MooolApp.Models.Mool", "_mool")
                        .WithOne("Address")
                        .HasForeignKey("MooolApp.Models.Address", "MoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_mool");
                });

            modelBuilder.Entity("MooolApp.Models.Item", b =>
                {
                    b.HasOne("MooolApp.Models.Mool", "_Mool")
                        .WithMany("Items")
                        .HasForeignKey("MoolID");

                    b.Navigation("_Mool");
                });

            modelBuilder.Entity("MooolApp.Models.Mool", b =>
                {
                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
